#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD)	+= devices_lge.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= ijb_lgu/
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= ijb_skt/

obj-$(CONFIG_LGE_QC_LCDC_LUT) += lge_qc_lcdc_luts.o
obj-$(CONFIG_LGE_KCAL) += lge_kcal_ctrl.o
obj-$(CONFIG_LGE_KCAL_QLUT) += kcal_qlut.o
